name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build framework and upload to release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh ./package.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: TapSDKSuite_*.zip
